### ISSUE TITLE
_pywrapfst.FstIOError: Read failed

### ISSUE THREAD

**Issue by aj7tesh** [Open-Speech-EkStep/speech-recognition-open-api#2]
I am trying to run server.py on my local after following all the installation and setup process as mentioned in documentation. But it looks like some where is setup is not done properly which I am unable to figure out.

Traceback (most recent call last):
  File "server.py", line 3, in <module>
    from speech_recognition_service import SpeechRecognizer
  File "/home/ajitesh/Desktop/workspace/asr/vakyans-server/speech-recognition-open-api/speech_recognition_service.py", line 3, in <module>
    from model_service import ModelService
  File "/home/ajitesh/Desktop/workspace/asr/vakyans-server/speech-recognition-open-api/model_service.py", line 3, in <module>
    from inverse_text_normalization.run_predict import inverse_normalize_text
  File "/home/ajitesh/anaconda3/envs/server-vakyansh/lib/python3.8/site-packages/inverse_text_normalization/run_predict.py", line 1, in <module>
    from inverse_text_normalization.hi.run_predict import inverse_normalize_text as hi_itn
  File "/home/ajitesh/anaconda3/envs/server-vakyansh/lib/python3.8/site-packages/inverse_text_normalization/hi/run_predict.py", line 18, in <module>
    from inverse_text_normalization.hi.inverse_normalize import INVERSE_NORMALIZERS
  File "/home/ajitesh/anaconda3/envs/server-vakyansh/lib/python3.8/site-packages/inverse_text_normalization/hi/inverse_normalize.py", line 26, in <module>
    from inverse_text_normalization.hi.taggers.tokenize_and_classify_final import ClassifyFinalFst
  File "/home/ajitesh/anaconda3/envs/server-vakyansh/lib/python3.8/site-packages/inverse_text_normalization/hi/taggers/tokenize_and_classify_final.py", line 20, in <module>
    from inverse_text_normalization.hi.graph_utils import GraphFst, delete_extra_space, delete_space
  File "/home/ajitesh/anaconda3/envs/server-vakyansh/lib/python3.8/site-packages/inverse_text_normalization/hi/graph_utils.py", line 53, in <module>
    suppletive = pynini.string_file(get_abs_path(data_path + 'suppletive.tsv'))
  File "extensions/_pynini.pyx", line 1042, in _pynini.string_file
  File "extensions/_pynini.pyx", line 1118, in _pynini.string_file
_pywrapfst.FstIOError: Read failed

**Comment by singhaki** [comment]
install indic-punct from here https://github.com/Open-Speech-EkStep/indic-punct . it solved the issue

**Comment by aj7tesh** [comment]
@singhaki I tried above explicitylt. Still the same error.
